### ISSUE TITLE
Docs: menu wrongly positioned (993<->1063px)

### ISSUE THREAD

**Issue by ThomDietrich** [eclipse/smarthome#1980]
On a smaller display with the Browser width between 993 and 1063px the menu get's "pushed away" by the logo:
![2016-08-07 00_52_58-fotos](https://cloud.githubusercontent.com/assets/2870104/17459456/5bff1986-5c39-11e6-90f6-b4b49a2db7e6.png)

I wanted to hack up a quick fix. Either of these are okay'ish solutions:

``` css
#header img#logo {
    height: 65px;
    width: 45%;
}
```

I'll have to look for a better solution though,  this only solves one problem but not the underlying cause.
